### ISSUE TITLE
How to register globally in Laravel?

### ISSUE THREAD

**Issue by HassanZahirnia** [salopot/image-generator#1]
First of all thanks for the great package! I just found out about it [here](https://github.com/fzaninotto/Faker/issues/1884#issuecomment-675547928) and started using it cause the original faker generator was lacking lots of options including an alternative for lorempixels.com and so on

I'm using Laravel and I wonder how can I have this provider be added to the original `$faker` so I don't have to write  these in every place?
```php
$faker = \Faker\Factory::create();
$imageProvider = new \Salopot\ImageGenerator\ImageProvider($faker);
$imageProvider->addImageSource(new \Salopot\ImageGenerator\ImageSources\Remote\PicsumPhotosSource($imageProvider));
$faker->addProvider($imageProvider);
```
I'm currently copy+pasting these few lines of codes in every Factory and Seeder file I have. I wish I could use the Laravel's built-in  magic (`$this->faker`) to work like `$this->faker->imageGenerator()`

I tried adding a custom provider as described [here](https://stackoverflow.com/a/38251529/996652) but it doesn't work quite well and is kinda messy and also gets confused with other 3rd party custom faker providers I have.

Do you happen to know a solution for this?

**Comment by salopot** [comment]
Hi @xperator ,
I think easiest way to register faker with new configuration: add next lines to the method **app/Providers/AppServiceProvider.php::register**
```
use Faker\Factory as FakerFactory;
use Faker\Generator as FakerGenerator;

***

$this->app->singleton(FakerGenerator::class, function ($app) {
    $generator =  FakerFactory::create($app['config']->get('app.faker_locale', 'en_US'));
    
    // Additional faker providers
    $imageProvider = new \Salopot\ImageGenerator\ImageProvider($generator);
    $imageProvider->addImageSource(new \Salopot\ImageGenerator\ImageSources\Local\SolidColorSource($imageProvider));
    $imageProvider->addImageSource(new \Salopot\ImageGenerator\ImageSources\Local\GallerySource($imageProvider, '/dir/with/images'));
    $imageProvider->addImageSource(new \Salopot\ImageGenerator\ImageSources\Local\SolidColorSource($imageProvider));
    $imageProvider->addImageSource(new \Salopot\ImageGenerator\ImageSources\Remote\LoremPixelSource($imageProvider));
    $imageProvider->addImageSource(new \Salopot\ImageGenerator\ImageSources\Remote\PicsumPhotosSource($imageProvider));
    $imageProvider->addImageSource(new \Salopot\ImageGenerator\ImageSources\Remote\UnsplashSource($imageProvider));
    $imageProvider->addImageSource(new \Salopot\ImageGenerator\ImageSources\Remote\PlaceKittenSource($imageProvider));
    $imageProvider->addImageSource(new \Salopot\ImageGenerator\ImageSources\Remote\PlaceImgSource($imageProvider));
    $generator->addProvider($imageProvider);

   return $generator;
});
```
And after that you can use faker (with ImageGenerator) in all standard laravel ways via DI: [factories](https://laravel.com/docs/master/database-testing#writing-factories), [resolve(\Faker\Generator::class)](https://laravel.com/docs/8.x/container#resolving), [constructor injection](https://laravel.com/docs/8.x/container#automatic-injection)

**Comment by HassanZahirnia** [comment]
@salopot Thanks a lot! Now it works like a charm anywhere. I appreciate it.
Not a big deal but just one tiny suggestion, I think a small `getFileName` function could be useful. For example in my case, I only save the photo's filename in the database, not the full path. For a solution I'm using [basename](https://laravel.com/docs/8.x/helpers#method-fluent-str-basename) atm to get the filename.

Anyway have a good day!
